### ISSUE TITLE
Provide built IPA for installation

### ISSUE THREAD

**Issue by Casuallynoted** [watanabexia/VRChatTracker#18]
Hello!

I wanted to suggest that you include a pre-built IPA under releases for folks who want to install it on their devices. Since I don't have a Mac, I can't compile it! :)

**Comment by xiatg** [comment]
Hi, thank you for your interest in VRChat Tracker. I have published a release with the `.ipa`. If you can, please let me know if you encounter any problem using it.

**Comment by Casuallynoted** [comment]
Thank you so much! I just installed the app and attempted to sign in but it gave an uncaught error message. I believe it may have to do with 2FA!

**Comment by xiatg** [comment]
Thanks for the feedback! Currently the app only supports email authentication. Are you by any chance using other 2FA methods?

**Comment by xiatg** [comment]
I just added OTP as a 2FA method in the latest release. Please try it out if you are still willing to.

**Comment by Casuallynoted** [comment]
Sorry just got free to respond! It does log in now! :D The app is awesome! I’ve noticed some crashes when changing tabs via the navigation bar, so I sent those as feedback via TestFlight!
